% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 17-Apr-2013 15:08:54
%  MATLAB version: 8.1.0.604 (R2013a)
% -------------------------------------------------------------------
saveVarsMat = load('applicationConfigSetProduction.mat');

applicationConfigSet = saveVarsMat.applicationConfigSet; % <1x1 Simulink.ConfigSet> Custom components not supported

clear saveVarsMat;
