function hall = hallBLY171D(positionInFirstState)
% Copyright 2013 The MathWorks, Inc.

name = 'Hall Effect Sensor on Anaheim Automation BLY171D';

description = sprintf([...
    'Phase A leads B leads C for counterclockwise rotation\n',...
    '-----------------------------------------------------\n',...
    'Hall A = Blue\n',...
    'Hall B = Green\n',...
    'Hall C = White\n',...
    'Gnd    = Black\n',...
    '+5V    = Red']);

docLink =  'http://www.anaheimautomation.com/manuals/brushless/L010228%20-%20BLY17%20Series%20Product%20Sheet.pdf';

positiveDirectionStates = [
    bin2dec('101')
    bin2dec('100')
    bin2dec('110')
    bin2dec('010')
    bin2dec('011')
    bin2dec('001')];

hall = createHall(...
          name,...
          description,...
          docLink,...
          positiveDirectionStates,...
          positionInFirstState);
      
